apiVersion: keptn.krateo.io/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/instance: project-sample
    app.kubernetes.io/part-of: keptn-provider
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: keptn-provider
  name: project-sample
spec:
  # TODO(user): Add fields here
