
apiVersion: keptn.krateo.io/v1alpha1
kind: Project
metadata:
  name: test-keptn-operator
  namespace: krateo-system
spec:
  api:
    url: https://<KEPTN_URL>/api
    tokenSecretRef:
      name: keptn-api-secret
      namespace: krateo-system
      key: token
  projectName: test-operator
  serviceName: test-operator
  git:
    url: https://<GIT_URL>/test-operator.git
    secretRef:
      name: git-api-secret
      namespace: krateo-system
      userKey: user1
      tokenKey: token
  shipyardRef:
    name: example-shipyard
    namespace: krateo-system
    key: content
---
apiVersion: keptn.krateo.io/v1alpha1
kind: Shipyard
metadata:
  name: example-shipyard
  namespace: krateo-system
spec:
  content: |
    apiVersion: "spec.keptn.sh/0.2.2"
    kind: "Shipyard"
    metadata:
      name: "shipyard"
    spec:
      stages:
        - name: "svil"
          sequences:
            - name: "delivery"
              tasks:
                - name: "tomcat-deployment"
                  properties:
                    deploymentstrategy: "direct"
            - name: "delivery-direct"
              tasks:
                - name: "tomcat-deployment"
                  properties:
                    deploymentstrategy: "user_managed"
            - name: "delivery-svil"
              tasks:
                - name: "tomcat-deployment"
                  properties:
                    deploymentstrategy: "user_managed"
        - name: "coll"
          sequences:
            - name: "delivery"
              tasks:
                - name: "tomcat-deployment"
                  properties:
                    deploymentstrategy: "direct"
            - name: "delivery-direct"
              tasks:
                - name: "tomcat-deployment"
                  properties:
                    deploymentstrategy: "user_managed"
            - name: "delivery-svil"
              tasks:
                - name: "tomcat-deployment"
                  properties:
                    deploymentstrategy: "user_managed"                
        - name: "prod"
          sequences:
            - name: "delivery"
              triggeredOn:
                - event: "svil.delivery.finished"
              tasks:
                - name: "tomcat-deployment"
                  properties:
                    deploymentstrategy: "blue_green_service"
            - name: "delivery-direct"
              tasks:
                - name: "tomcat-deployment"
                  properties:
                    deploymentstrategy: "user_managed"
            - name: "remediation"
              triggeredOn:
                - event: "prod.remediation.finished"
                  selector:
                    match:
                      evaluation.result: "fail"
              tasks:
                - name: "tomcat-get-action"
                - name: "tomcat-action"
                - name: "tomcat-evaluation"
                  triggeredAfter: "2m"
                  properties:
                    timeframe: "2m"